name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Semantic version range syntax or exact version of a Python version
    - name: Set up Python environment
      run: pip install -r requirements.txt
    - name: Run builder.py
      run: python builder.py
    - name: Git config, commit and push
      run: |
         git config user.name 'Omar Vasquez Lima'
         git config user.email 'omar.vasquezlima@gmail.com'
         git add index.html
         git commit -m 'Build commit.'
         git push
#     - name: publish-to-git
#       uses: seanmiddleditch/gha-publish-to-git@v1
#       with:
#         branch: master
#         repository: oevl/ghpages-python-ghactions
#         github_pat: '${{ secrets.GH_PAT }}'
#         commit_author: 'omar.vasquezlima@gmail.com'
#         if: success() && github.event == 'push
